server:
  port: 9003
  servlet:
    context-path: /demo
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
    address: 127.0.0.1

spring:
  profiles:
    active: dev
    security: false

  datasource:
        # url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
        url: jdbc:mysql://localhost:3306/activiti5?useUnicode=true&characterEncoding=utf-8&useSSL=true&useTimezone=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        username: root
        password: 951103cgr
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        logSlowSql: true
        # Druid StatViewServlet??
        druid:
          stat-view-servlet:
            # ??true ????????/druid/index.html
            enabled: true
            url-pattern: /druid/*
            # ????????
            reset-enable: true
            login-username: admin
            login-password: adminservice
            # IP??? ??????
            allow:
            # IP???
            deny:
          filter:
            stat:
              # ???sql ?????3???
              log-slow-sql: true
  # ???
  activiti:
    check-process-definitions: false
    db-identity-used: false
    # ????Activiti??? ????????????????
    database-schema-update: false
    history-level: full
    # ???activiti???????? ActivitiDbConfig
    #    datasource:
    #      jdbcUrl: jdbc:mysql://192.168.3.201:3306/xboot-oa-online?useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    #      username: tech
    #      password: ENC(uqbQ+2CbKXvzyaEZK8DP6AVVJpm2yfhJ)
    #      type: com.alibaba.druid.pool.DruidDataSource
    #      driverClassName: com.mysql.cj.jdbc.Driver
    # ????
    xboot:
      # ????? ????
      activityFontName: Microsoft YaHei UI
      labelFontName: Microsoft YaHei UI
  #autoconfigure:
    #exclude: org.activiti.spring.boot.DataSourceProcessEngineAutoConfiguration
  #main:
    #allow-bean-definition-overriding: true


ignored:
  urls:
    - /editor-app/**