version: '3.8'

services:
  # MySQL 服务
  mysql:
    image: mysql:8.0
    container_name: mysql_project1
    environment:
      MYSQL_ROOT_PASSWORD: xx  # 设置 root 用户的密码
      MYSQL_DATABASE: xx  # 设置数据库名称
      #MYSQL_USER: root                # 设置数据库用户
      MYSQL_PASSWORD: xx       # 设置数据库用户的密码
    ports:
      - "3306:3306"  # 映射端口
    volumes:
      - /software/project1/mysql_data:/var/lib/mysql  # 持久化 MySQL 数据库
    networks:
      - my_network

  # Spring Boot 后端服务
  springboot:
    image: openjdk:8u312-jdk  # 使用 JDK 8 镜像
    container_name: springboot_project1
    environment:
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk
    volumes:
      - /software/project1:/app  # 将 /software/project1 目录挂载到容器内的 /app
    networks:
      - my_network
    command: java -jar /app/oa-1.0.jar  # 启动 oa-1.0.jar
    depends_on:
      - mysql  # 确保 MySQL 服务先启动

  # Nginx 反向代理
  nginx:
    image: nginx:latest
    container_name: nginx_project1
    ports:
      - "8081:80"  # 映射 Nginx 服务的 80 端口到宿主机的 8081 端口
    volumes:
      - /software/project1/nginx.conf:/etc/nginx/nginx.conf  # 挂载自定义的 nginx 配置文件
      - /software/project1/www:/usr/share/nginx/html  # 挂载前端静态文件
    networks:
      - my_network
      
  # Redis 服务
  redis:
    image: redis:latest  # 使用官方 Redis 镜像
    container_name: redis_oa
    ports:
      - "6379:6379"  # 映射 Redis 服务的 6379 端口
    volumes:
      - /software/ox/redis_data:/data  # 持久化 Redis 数据
    networks:
      - my_network    

networks:
  my_network:
    driver: bridge
